name: dart_language_server
version: 0.0.13
description: >-
  A shim on the analysis server following the language server protocol
homepage: https://github.com/natebosch/dart_language_server
authors:
  - Nate Bosch <nbosch1@gmail.com>

environment:
  sdk: ">=1.8.0 <2.0.0"

dependencies:
  async: ^1.11.3
  json_rpc_2: ^2.0.3
  logging: ^0.11.3
  path: ^1.4.1
  stream_channel: ^1.5.0
  stream_transform: ^0.0.3

dev_dependencies:
  build: ^0.9.0
  build_runner: ^0.3.0
  dart_style: ^1.0.7
  test: ^0.12.18
  yaml: ^2.1.12

executables:
  dart_language_server: dart_language_server
